import React from 'react';

// You don't need all the Lucide icons for this page, but we'll import CheckCircle for style consistency
import { AlertTriangle, CheckCircle } from 'lucide-react'; 
import { WEBSITE_NAME } from "../config/constants";

const DisclaimerPage = () => {
  const AppName ={WEBSITE_NAME}  ; // Placeholder for your App Name
  const WebsiteUrl = "[Your Website URL]"; // Placeholder for your Website URL
  
  return (
    <>
      {/* Hero Section - Matching ContactUsPage Header Style */}
      <header className="py-20 bg-gradient-to-r from-purple-800 to-purple-600 text-white shadow-md">
        <div className="max-w-7xl py-20 mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-5xl font-extrabold mb-3">Official Disclaimer</h1>
          <p className="text-xl text-purple-200">
            Important information regarding the use of our AI-powered preparation platform.
          </p>
        </div>
      </header>

      {/* Main Content (Disclaimer Sections) - Matching ContactUsPage Section Style */}
      <section className="py-16 md:py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white p-8 lg:p-12 rounded-2xl shadow-2xl border border-gray-100 text-gray-700">
            
            {/* --- AI-Specific IELTS Disclaimer (New Section) --- */}
            <div className="mb-10 pb-6 border-b border-purple-200">
              <div className="flex items-center mb-4">
                <h2 className="text-3xl font-bold text-gray-800">
                 Disclaimer
                </h2>
              </div>
              <p className="mb-4 text-lg">
               {WEBSITE_NAME}  is an AI-powered IELTS preparation tool designed to make your learning simple, time-saving, and hassle-free.

Please note that this platform is not a replacement for real-life IELTS classes, certified trainers, or official test preparation. The guidance and feedback provided are generated by AI for practice and educational purposes only.

We do not guarantee the same experience or results as professional instruction, and no comparison should be made between this AI system and real-life teaching methods.

Our goal is to help you practice conveniently, save money and time, and build confidence — but your final success depends on your personal effort and consistent study.
              </p>
              
              <ul className="space-y-3 pl-5 list-inside text-gray-600">
                <li className="flex items-start">
                  <span className="text-red-600 font-bold mr-2 text-xl mt-[-2px]">•</span>
                  Please note that this platform is not a replacement for real-life IELTS classes, certified trainers, or official test preparation.
                </li>
                <li className="flex items-start">
                  <span className="text-red-600 font-bold mr-2 text-xl mt-[-2px]">•</span>
                  The guidance and feedback provided are generated by AI for practice and educational purposes only.
                </li>
                <li className="flex items-start">
                  <span className="text-red-600 font-bold mr-2 text-xl mt-[-2px]">•</span>
                  We do not guarantee the same experience or results as professional instruction, and no comparison should be made between this AI system and real-life teaching methods.
                </li>
                <li className="flex items-start">
                  <span className="text-red-600 font-bold mr-2 text-xl mt-[-2px]">•</span>
                  Our goal is to help you practice conveniently, save money and time, and build confidence — but your final success depends on your personal effort and consistent study.
                </li>
              </ul>
            </div>

            {/* --- General Disclaimer Section (Adjusted Style) --- */}
            <div className="mb-10 pb-6 border-b border-gray-200">
              <h2 className="text-2xl font-bold text-purple-700 mb-4">
                1. General Information Disclaimer
              </h2>
              <p className="text-gray-600">
                The information provided by {WEBSITE_NAME}  is for general informational purposes only. All information on the Site is provided in good faith. However, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site. Your use of the Site and your reliance on any information is solely at your own risk.
              </p>
            </div>

            {/* --- Not Professional Advice Section --- */}
            <div className="mb-10 pb-6 border-b border-gray-200">
              <h2 className="text-2xl font-bold text-purple-700 mb-4">
                2. Not Professional Advice
              </h2>
              <p className="text-gray-600">
                The Site cannot and does not contain professional advice. The information is provided for general informational and educational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of professional advice (e.g., medical, legal, financial, or specific exam advice beyond AI guidance).
              </p>
            </div>

            {/* --- External Links Disclaimer --- */}
            <div className="mb-10 pb-6">
              <h2 className="text-2xl font-bold text-purple-700 mb-4">
                3. External Links Disclaimer
              </h2>
              <p className="text-gray-600">
                The Site may contain links to other websites or content belonging to third parties. Such external links are not investigated, monitored, or checked for accuracy by us. We DO NOT WARRANT, ENDORSE, OR ASSUME RESPONSIBILITY for the reliability of any information offered by third-party websites linked through the Site.
              </p>
            </div>

            

          </div>
        </div>
      </section>
    </>
  );
};

export default DisclaimerPage;